# Generated by Django 3.0.3 on 2020-03-18 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0002_feedbackmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='values',
            field=models.CharField(default='1,2,3,4,5,6,7,8,9,10', max_length=64),
        ),
    ]
