# Generated by Django 3.0.3 on 2020-02-21 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0003_category_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gamification.Category'),
        ),
        migrations.AlterUniqueTogether(
            name='transaction',
            unique_together=set(),
        ),
    ]
