# Generated by Django 3.0.3 on 2020-03-26 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0007_auto_20200326_1239'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderProduct',
            new_name='OrdProduct',
        ),
    ]
