# Generated by Django 3.0.3 on 2020-03-26 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0008_auto_20200326_1241'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrdProduct',
        ),
    ]
