# Generated by Django 3.0.3 on 2020-03-26 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0009_delete_ordproduct'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
